
CREATE DATABASE BB_DB;
CREATE TABLE Event (
	EventID	INTEGER NOT NULL,
	EventTile	TEXT NOT NULL,
	EventTime	TIME NOT NULL,
	EventDate	DATE NOT NULL,
	EventDisc	TEXT NOT NULL,
	EventSummary	TEXT NOT NULL,
	EventStatus	TEXT NOT NULL,
	EventCatagory	TEXT NOT NULL,
	EventAddress	TEXT NOT NULL,
	EventCity	TEXT NOT NULL,
	EventImg	TEXT NOT NULL,
	EventTicketQty	INTEGER NOT NULL,
	BookingID	INTEGER NOT NULL,
	CommentID	INTEGER NOT NULL,
	UserID	INTEGER NOT NULL,
	PRIMARY KEY(EventID)
    
    );
    COMMIT;


